### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by Wathis** [ewino/qreader#6]
I have a problem while scanning this QRCode : 

![qrcode](https://user-images.githubusercontent.com/23291448/35402450-ee4ffb42-01fc-11e8-9393-9826a8861516.png)

By using 
`import qreader`
`qreader.read("qrcode.png")`

The issue  : 
```

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/qreader/api.py", line 26, in read
    return QRDecoder(data).get_first()
  File "/Library/Python/2.7/site-packages/qreader/decoder.py", line 21, in get_first
    return self._decode_next_message()
  File "/Library/Python/2.7/site-packages/qreader/decoder.py", line 31, in _decode_next_message
    return self._decode_message(mode)
  File "/Library/Python/2.7/site-packages/qreader/decoder.py", line 47, in _decode_message
    raise IllegalQrMessageModeId(mode)
qreader.exceptions.IllegalQrMessageModeId: Unknown mode ID: 0
```

**Comment by ewino** [comment]
Hi Wathis, thanks for letting me know!
I'm currently without access to my computer, but I'll take a look when I
get back home next week.

Have a lovely weekend,
ewino
